@ echo off
REM HEADER FOR WINDOW SYSTEMS
REM Project: ak-size-estimation Azure Kinect Size Estimation https://github.com/juancarlosmiranda/ak_size_weight_sim/
REM
REM  * PAgFRUIT http://www.pagfruit.udl.cat/en/
REM  * GRAP http://www.grap.udl.cat/
REM
REM  Author: Juan Carlos Miranda. https://github.com/juancarlosmiranda/

SET APPLICATION_FOLDER_MAIN=ak_sw_benchmarker
SET APPLICATION_FOLDER_OUT=ak_sw_benchmarker_f
SET APPLICATION_PATH=%~dp0
SET VERSION=0.0.9

SET CONF_NAME=*.conf
SET PATH_FOLDER_RELATIVE_CONF=src\%APPLICATION_FOLDER_MAIN%\conf\
SET PATH_CONF_FILE=%APPLICATION_PATH%%PATH_FOLDER_RELATIVE_CONF%%CONF_NAME%
SET DESTINATION_FOLDER_RELATIVE_CONF=dist\%APPLICATION_FOLDER_OUT%\conf
SET DESTINATION_FOLDER_ABSOLUTE_CONF=%APPLICATION_PATH%%DESTINATION_FOLDER_RELATIVE_CONF%


SET ASSETS_NAME=*.png
SET PATH_FOLDER_RELATIVE_ASSETS=src\gui_frame_ext\assets\
SET PATH_ASSETS_FILE=%APPLICATION_PATH%%PATH_FOLDER_RELATIVE_ASSETS%%ASSETS_NAME%
SET DESTINATION_FOLDER_RELATIVE_ASSETS=dist\%APPLICATION_FOLDER_OUT%\gui_frame_ext\assets\
SET DESTINATION_FOLDER_ABSOLUTE_ASSETS=%APPLICATION_PATH%%DESTINATION_FOLDER_RELATIVE_ASSETS%



ECHO %APPLICATION_PATH%
ECHO %PATH_CONF_FILE%
ECHO %DESTINATION_FOLDER_ABSOLUTE_CONF%

ECHO %PATH_ASSETS_FILE%
ECHO %DESTINATION_FOLDER_ABSOLUTE_ASSETS%

py -m build

ECHO 'pip package is OK -- '/%DIST_FOLDER%/%APPLICATION_FOLDER_MAIN%-%VERSION%'-py3-none-any.whl
ECHO 'UPLOAD FOR TEST PACKAGE USING - twine upload --repository testpypi ./dist/*'
ECHO 'UPLOAD FINAL PACKAGE USING - twine upload ./dist/* --verbose'